// Generated by CoffeeScript 2.3.1
var AhoCorasick, Tests;

Tests = module.exports;

AhoCorasick = require('..');

console.log(__filename);

Tests['Picks out chinese words'] = function(test) {
  var ac, content, find_list, i, len, ref, word;
  ac = new AhoCorasick();
  ref = ['五毛党', '国家', '黑手党', '党国', '毛五贴'];
  for (i = 0, len = ref.length; i < len; i++) {
    word = ref[i];
    ac.add(word);
  }
  ac.build_fail();
  find_list = ['毛五贴', '五毛党', '党国', '国家'];
  content = '宋国毛五贴五毛党国家是谁啊';
  ac.search(content, function(found_word, data, offset) {
    return test.equal(content.substr(offset, found_word.length), found_word);
  });
  test.expect(find_list.length);
  return test.done();
};
